"""Agent runtime registry and doctor checks."""

from .registry import (
    AGENT_SPECS,
    AGENT_PROVIDER_BINDINGS,
    AgentCompatibility,
    AgentBinding,
    DispatchReadiness,
    AgentSpec,
    CommandOutput,
    DoctorCheck,
    DoctorResult,
    PROVIDER_PROFILES,
    ProviderProfile,
    assess_agent_compatibility,
    assess_dispatch_readiness,
    doctor_agent,
    get_provider_profile,
    get_agent_spec,
    list_agent_compatibility,
    list_provider_profiles,
    list_agent_specs,
    resolve_agent_binding,
)

__all__ = [
    "AGENT_SPECS",
    "AGENT_PROVIDER_BINDINGS",
    "AgentCompatibility",
    "AgentBinding",
    "DispatchReadiness",
    "AgentSpec",
    "CommandOutput",
    "DoctorCheck",
    "DoctorResult",
    "PROVIDER_PROFILES",
    "ProviderProfile",
    "assess_agent_compatibility",
    "assess_dispatch_readiness",
    "doctor_agent",
    "get_provider_profile",
    "get_agent_spec",
    "list_agent_compatibility",
    "list_provider_profiles",
    "list_agent_specs",
    "resolve_agent_binding",
]
